services:
  backend:
    container_name: teachers-coach-teachers-backend
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      # - DATABASE_URL=postgresql://user:password@db:5432/tct_database
      # - SQLALCHEMY_DATABASE_URI=postgresql://postgres:Smile123!@db:5432/tct_database
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tct_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # - POSTGRES_USER=user
      # - POSTGRES_PASSWORD=password
      # - POSTGRES_DB=tct_database
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
