services:
  backend:
    container_name: teachers-coach-teachers-backend
    env_file:
      - .env
    build:
      context: ./flask_app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=flask_app/run.py
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - PYTHONPATH=/app
    user: "${UID}:${GID}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: tct_postgres
    volumes:
      - tct_postgres_data:/var/lib/postgresql/data
    # Leave ports here even if commented out. Allows for easy debugging/direct connecting to the database locally
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 2s
      retries: 15
      start_period: 1s

  expo-frontend:
    container_name: expo-frontend
    build:
      context: ./mobile
    ports:
      - "19000:19000"  # Metro Bundler
      - "19001:19001"  # WebSocket debugger
      - "19002:19002"  # Expo DevTools
      - "8081:8081"    # React Native packager
    volumes:
      - ./mobile:/app
      - /app/node_modules
    command: npx expo start --tunnel
    user: "${UID}:${GID}"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_PUBLIC_HOST=${EXPO_PUBLIC_HOST}
      - EXPO_NO_CHROME=true
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0

#  expo-frontend:
#    container_name: expo-frontend
#    build:
#      context: ./mobile
#    ports:
#      - "19000:19000"
#      - "8081:8081"
#    volumes:
#      - ./mobile:/app
#      - /app/node_modules
#    command: npx expo start
#    user: "${UID}:${GID}"
#    environment:
#      - NODE_ENV=development

volumes:
  tct_postgres_data:
