version: "3.8"
services:
  backend:
    container_name: flask-app
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"

  expo-frontend:
    container_name: expo-frontend
    build:
      context: ./mobile
    ports:
      - "19000:19000"
      - "8081:8081"
    volumes:
      - ./mobile:/app
      - /app/node_modules
      - ./state.json:/.expo/state.json
    stdin_open: true
    tty: true
    command: npx expo start --host lan
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
