services:
  backend:
    container_name: teachers-coach-teachers-backend
    env_file:
      - .env
    build: 
      context: ./flask_app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=flask_app/run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - PYTHONPATH=/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tct_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB={$POSTGRES_DB}

  expo-frontend:
    container_name: expo-frontend
    build:
      context: ./mobile
    ports:
      - "19000:19000"
      - "8081:8081"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    command: npx expo start
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
