"""Create credits table

Revision ID: 5719e9171339
Revises: ded767144496
Create Date: 2024-12-24 18:11:53.524768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5719e9171339'
down_revision = 'ded767144496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_redemptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('redeemed_by', sa.String(length=36), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_positive_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_redemptions_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_redemptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_redemptions_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_redemptions_redeemed_by'), ['redeemed_by'], unique=False)
        batch_op.create_index('ix_unique_active_code', ['code', 'redeemed_by'], unique=True, postgresql_where=sa.text('redeemed_by IS NULL'))

    op.create_table('credit_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_user_id', sa.String(length=36), nullable=False),
    sa.Column('to_user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('transfer_type', sa.Enum('REDEMPTION', 'MENTORSHIP', 'PURCHASE', name='transfertype'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_positive_amount'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_transfers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transfers_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transfers_to_user_id'), ['to_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transfers_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transfers_from_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transfers_created_at'))

    op.drop_table('credit_transfers')
    with op.batch_alter_table('credit_redemptions', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_active_code', postgresql_where=sa.text('redeemed_by IS NULL'))
        batch_op.drop_index(batch_op.f('ix_credit_redemptions_redeemed_by'))
        batch_op.drop_index(batch_op.f('ix_credit_redemptions_created_by'))
        batch_op.drop_index(batch_op.f('ix_credit_redemptions_created_at'))
        batch_op.drop_index(batch_op.f('ix_credit_redemptions_code'))

    op.drop_table('credit_redemptions')
    # ### end Alembic commands ###
