"""Add vector table

Revision ID: 883b5867cba1
Revises: c385fdc64475
Create Date: 2025-02-24 18:36:38.174369

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '883b5867cba1'
down_revision = 'c385fdc64475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_vectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_vectors', schema=None) as batch_op:
        batch_op.create_index('idx_mentor_vectors_embedding', ['embedding'], unique=False, postgresql_using='ivfflat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_vectors', schema=None) as batch_op:
        batch_op.drop_index('idx_mentor_vectors_embedding', postgresql_using='ivfflat')

    op.drop_table('mentor_vectors')
    # ### end Alembic commands ###
