"""Add embeddings

Revision ID: c385fdc64475
Revises: 
Create Date: 2025-02-24 18:30:08.747577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c385fdc64475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('first_name')
        batch_op.drop_column('expertise_areas')
        batch_op.drop_column('vector_embedding')
        batch_op.drop_column('last_name')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vector_embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expertise_areas', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('profile_data')

    # ### end Alembic commands ###
